export const CREATE_BILL_REQUEST='CREATE_BILL_REQUEST';
export const CREATE_BILL_SUCCESS='CREATE_BILL_SUCCESS';
export const CREATE_BILL_FAIL='CREATE_BILL_FAIL';
export const GET_BILL_DATA_REQUEST='GET_BILL_DATA_REQUEST';
export const GET_BILL_DATA_SUCCESS='GET_BILL_DATA_SUCCESS';
export const GET_BILL_DATA_FAIL='GET_BILL_DATA_FAIL';


export const CLEAR_ERROR="CLEAR_ERROR"